### ISSUE TITLE
NullPoint...が発生

### ISSUE THREAD

**Issue by Naomath** [Naomath/MyApplication_app_contest#10]
ListGroupWordsActivityでNullPointExceptionが発生
27行目で
08-01 21:49:20.186 20429-20429/com.lifeistech.naoto.myapplication_app_contest 

```エラー全文
E/AndroidRuntime: FATAL EXCEPTION:
Process: com.lifeistech.naoto.myapplication_app_contest, PID: 20429
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lifeistech.naoto.myapplication_app_contest/com.lifeistech.naoto.myapplication_app_contest.ListGroupWordsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                                                                                                    at com.lifeistech.naoto.myapplication_app_contest.ListGroupWordsActivity.onCreate(ListGroupWordsActivity.java:27)
                                                                                                    at android.app.Activity.performCreate(Activity.java:6237)
                                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by halu5071** [comment]
じゃあなおとには、ブレークポイントとデバッグモードの使い方を教えよう

http://qiita.com/kazy/items/252bfc2d88d8899a95d5#android-studio%E3%81%A7%E3%83%96%E3%83%AC%E3%83%BC%E3%82%AF%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%82%92%E4%BB%95%E8%BE%BC%E3%82%93%E3%81%A7%E6%AD%A2%E3%82%81%E3%82%8B

http://qiita.com/FumihikoSHIROYAMA/items/e3159103ba2fba07e063

これを参考にするといい。これを使えば、どの変数にどんな値が入っていて、どこが`null`なのかすぐに分かるよ！

**Comment by Naomath** [comment]
色々debugしましたが、保存するときにはArrayListもStringの変数は渡ってる。
しかし、呼び出すときにはStringの変数は呼び出せているが、ArrayListはnullのよう。
ちなみにstackoverfallowによるとhashmapはSugarOrmで保存できないらしい。

**Comment by Naomath** [comment]
保存体系を変える可能性もあり

**Comment by Naomath** [comment]
cloneしてないことに気づいた
