### ISSUE TITLE
java.lang.indexoutofboundsexceptionというエラー

### ISSUE THREAD

**Issue by Naomath** [Naomath/MyApplication_app_contest#8]
SetUpActivityの、グループを全体で登録するメソッドにエラーが起きた

07-26 21:03:07.148 11962-11962/com.lifeistech.naoto.myapplication_app_contest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                Process: com.lifeistech.naoto.myapplication_app_contest, PID: 11962
                                                                                                java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
                                                                                                    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                                    at java.util.ArrayList.get(ArrayList.java:308)
                                                                                                    at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:344)
                                                                                                    at com.lifeistech.naoto.myapplication_app_contest.SetUpActivity$4.onClick(SetUpActivity.java:141)
                                                                                                    at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

TwoWordsForSet twoWordsForSet = (TwoWordsForSet)adapter.getItem(i2);

という、エラーメッセジとエラーの原因である。
いろいろ調べてみたが、わからない。
listViewに関連すると再描画するときにエラーが起こることはあるらしい。

**Comment by halu5071** [comment]
https://github.com/Naomath/MyApplication_app_contest/commit/247597d30385ecc85fba9c1eb56e1f25fb9cdc8c
ここに解決方法載っけたので見てね！
